# Generated by Django 5.2.13 on 2026-05-04 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('executive', 'Executive summary'), ('server', 'Server vulnerabilities'), ('application', 'Application vulnerabilities'), ('critical', 'Critical CVEs'), ('kev', 'CISA KEV'), ('fix_available', 'Fix available'), ('open', 'Open vulnerabilities')], max_length=32)),
                ('output_format', models.CharField(choices=[('html', 'HTML'), ('json', 'JSON'), ('csv', 'CSV'), ('pdf', 'PDF')], max_length=16)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
