# Generated by Django 5.2.13 on 2026-05-04 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('ssh_port', models.PositiveIntegerField(default=22)),
                ('username', models.CharField(max_length=255)),
                ('authentication_type', models.CharField(choices=[('password', 'Password'), ('private_key', 'Private key')], max_length=32)),
                ('encrypted_password', models.TextField(blank=True)),
                ('encrypted_private_key', models.TextField(blank=True)),
                ('encrypted_sudo_password', models.TextField(blank=True)),
                ('environment', models.CharField(choices=[('production', 'Production'), ('staging', 'Staging'), ('development', 'Development'), ('test', 'Test')], default='production', max_length=32)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_connection_status', models.CharField(choices=[('unknown', 'Unknown'), ('success', 'Success'), ('failed', 'Failed')], default='unknown', max_length=32)),
                ('last_successful_connection_at', models.DateTimeField(blank=True, null=True)),
                ('credential_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=500)),
                ('project_type', models.CharField(blank=True, max_length=120)),
                ('framework', models.CharField(blank=True, max_length=120)),
                ('language', models.CharField(blank=True, max_length=120)),
                ('dependency_files', models.JSONField(blank=True, default=list)),
                ('git_repository_url', models.URLField(blank=True)),
                ('git_branch', models.CharField(blank=True, max_length=255)),
                ('git_commit_hash', models.CharField(blank=True, max_length=120)),
                ('package_manager', models.CharField(blank=True, max_length=120)),
                ('dockerfile_present', models.BooleanField(default=False)),
                ('docker_compose_present', models.BooleanField(default=False)),
                ('last_discovered_at', models.DateTimeField(blank=True, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='servers.server')),
            ],
            options={
                'ordering': ['name', 'path'],
                'unique_together': {('server', 'path')},
            },
        ),
    ]
