# Generated by Django 5.2.13 on 2026-05-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='codebase_paths',
            field=models.TextField(blank=True, default='/var/www\n/srv/apps\n/opt/apps\n/home\n/app'),
        ),
    ]
