# Generated by Django 5.2.13 on 2026-05-04 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scanners', '0001_initial'),
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SBOMArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.CharField(default='syft', max_length=64)),
                ('format', models.CharField(default='json', max_length=32)),
                ('file_path', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('package_count', models.PositiveIntegerField(default=0)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sboms', to='servers.application')),
                ('related_scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sboms', to='scanners.scanjob')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sboms', to='servers.server')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
