# Generated by Django 5.2.13 on 2026-05-04 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('scan_os_packages', models.BooleanField(default=True)),
                ('scan_application_directories', models.BooleanField(default=True)),
                ('scan_docker_images', models.BooleanField(default=False)),
                ('scan_containers', models.BooleanField(default=False)),
                ('scan_dependency_manifests', models.BooleanField(default=True)),
                ('scan_iac_files', models.BooleanField(default=True)),
                ('scan_shell_scripts', models.BooleanField(default=True)),
                ('enable_syft', models.BooleanField(default=True)),
                ('enable_grype', models.BooleanField(default=True)),
                ('enable_trivy', models.BooleanField(default=True)),
                ('include_dev_dependencies', models.BooleanField(default=False)),
                ('severity_threshold', models.CharField(choices=[('unknown', 'Unknown'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('include_paths', models.TextField(blank=True)),
                ('exclude_paths', models.TextField(blank=True)),
                ('schedule', models.CharField(choices=[('manual', 'Manual only'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='manual', max_length=16)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScannerInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('not_installed', 'Not installed'), ('installing', 'Installing'), ('installed', 'Installed'), ('failed', 'Failed')], default='not_installed', max_length=32)),
                ('syft_version', models.CharField(blank=True, max_length=64)),
                ('grype_version', models.CharField(blank=True, max_length=64)),
                ('trivy_version', models.CharField(blank=True, max_length=64)),
                ('last_install_date', models.DateTimeField(blank=True, null=True)),
                ('install_logs', models.TextField(blank=True)),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scanner_installation', to='servers.server')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('queue_name', models.CharField(choices=[('default', 'Default'), ('install', 'Tool installation'), ('discovery', 'Application discovery'), ('scan', 'Scan execution')], default='scan', max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('completed_with_warnings', 'Completed with warnings'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=32)),
                ('tools_used', models.JSONField(blank=True, default=list)),
                ('raw_output_path', models.CharField(blank=True, max_length=500)),
                ('parsed_findings', models.JSONField(blank=True, default=list)),
                ('error_logs', models.TextField(blank=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_jobs', to='servers.application')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_jobs', to='servers.server')),
                ('scan_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_jobs', to='scanners.scanprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
