# Generated by Django 5.2.13 on 2026-05-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='cancellation_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='stage',
            field=models.CharField(choices=[('queued', 'Queued'), ('claimed', 'Claimed by worker'), ('installing_tools', 'Installing tools'), ('discovering_apps', 'Discovering apps'), ('preparing_target', 'Preparing target'), ('building_sbom', 'Building SBOM'), ('running_grype', 'Running Grype'), ('running_trivy', 'Running Trivy'), ('parsing_results', 'Parsing results'), ('completed', 'Completed'), ('cancel_requested', 'Cancel requested'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='queued', max_length=32),
        ),
    ]
