# Generated by Django 5.2.13 on 2026-05-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0002_scanjob_cancellation_requested_scanjob_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='current_command',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='progress_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
