# Generated by Django 5.2.13 on 2026-05-04 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0003_scanjob_current_command_scanjob_progress_context_and_more'),
        ('servers', '0002_server_codebase_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannerinstallation',
            name='lynis_version',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='scannerinstallation',
            name='openscap_version',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='scanprofile',
            name='enable_lynis',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scanprofile',
            name='enable_openscap',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scanprofile',
            name='openscap_profile',
            field=models.CharField(default='xccdf_org.ssgproject.content_profile_cis_level1_server', max_length=255),
        ),
        migrations.AlterField(
            model_name='scanjob',
            name='stage',
            field=models.CharField(choices=[('queued', 'Queued'), ('claimed', 'Claimed by worker'), ('installing_tools', 'Installing tools'), ('discovering_apps', 'Discovering apps'), ('preparing_target', 'Preparing target'), ('building_sbom', 'Building SBOM'), ('running_grype', 'Running Grype'), ('running_trivy', 'Running Trivy'), ('running_lynis', 'Running Lynis'), ('running_openscap', 'Running OpenSCAP'), ('parsing_results', 'Parsing results'), ('completed', 'Completed'), ('cancel_requested', 'Cancel requested'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='queued', max_length=32),
        ),
        migrations.CreateModel(
            name='ComplianceFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_scanner', models.CharField(max_length=32)),
                ('benchmark', models.CharField(blank=True, max_length=255)),
                ('control_id', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('resource', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('remediation', models.TextField(blank=True)),
                ('references', models.JSONField(blank=True, default=list)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted_risk', 'Accepted risk'), ('false_positive', 'False positive'), ('fixed', 'Fixed'), ('ignored', 'Ignored')], default='open', max_length=32)),
                ('raw_output', models.TextField(blank=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_findings', to='servers.application')),
                ('scan_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_findings', to='scanners.scanjob')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_findings', to='servers.server')),
            ],
            options={
                'ordering': ['-last_seen', '-created_at'],
            },
        ),
    ]
