# Generated by Django 5.2.13 on 2026-05-04 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0004_scannerinstallation_lynis_version_and_more'),
        ('servers', '0002_server_codebase_paths'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledScanDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_dispatches', to='scanners.scanprofile')),
                ('scan_job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_dispatch', to='scanners.scanjob')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_dispatches', to='servers.server')),
            ],
            options={
                'ordering': ['-window_start', 'server__name'],
                'unique_together': {('profile', 'server', 'window_start', 'window_end')},
            },
        ),
    ]
