# Generated by Django 5.2.13 on 2026-05-04 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scanners', '0001_initial'),
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VulnerabilityFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cve_id', models.CharField(db_index=True, max_length=64)),
                ('source_scanner', models.CharField(max_length=32)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('cvss_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('package_name', models.CharField(max_length=255)),
                ('installed_version', models.CharField(blank=True, max_length=255)),
                ('fixed_version', models.CharField(blank=True, max_length=255)),
                ('package_type', models.CharField(blank=True, max_length=120)),
                ('ecosystem', models.CharField(blank=True, max_length=120)),
                ('affected_path', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('references', models.JSONField(blank=True, default=list)),
                ('fix_available', models.BooleanField(default=False)),
                ('exploit_known', models.BooleanField(default=False)),
                ('cisa_kev', models.BooleanField(default=False)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted_risk', 'Accepted risk'), ('false_positive', 'False positive'), ('fixed', 'Fixed'), ('ignored', 'Ignored')], default='open', max_length=32)),
                ('remediation_notes', models.TextField(blank=True)),
                ('raw_output', models.TextField(blank=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='servers.application')),
                ('scan_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='scanners.scanjob')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='servers.server')),
            ],
            options={
                'ordering': ['-last_seen', '-created_at'],
            },
        ),
    ]
